[package]
name = "sftrace"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = [ "cdylib" ]

[[bin]]
name = "sftrace"

[dependencies]
# tools
anyhow = "1"
argh = "0.1"
addr2line = "0.24"
rayon = "1"
flate2 = "1"
prost = "0.13"
micromegas-perfetto = "0.7"
parking_lot = "0.12"

# perf
quanta = "0.12"

# xray patch
libc = "0.2"
findshlibs = "0.10"
object = "0.36"
zerocopy = { version = "0.8", features = [ "derive" ] }
memmap2 = "0.9"

[profile.release]
panic = "abort"
debug = true
