[package]
name = "sftrace"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = [ "cdylib" ]

[dependencies]
anyhow = "1"
libc = "0.2"
quanta = "0.12"

# xray patch
findshlibs = "0.10"
object = "0.36"
zerocopy = { version = "0.8", features = [ "derive" ] }
memmap2 = "0.9"

[profile.release]
panic = "abort"
debug = true
